spring.application.name=demo

spring.datasource.url=jdbc:postgresql://${SUPABASE_DB_URL}/postgres?user=${SUPABASE_DB_USERNAME}&password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Don't forget to comment in security in your properties